//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpClientConsoleTestApp.SOAWebServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WebServices.thesis.enesuysal.ist/", ConfigurationName="SOAWebServiceReference.JavaWebService")]
    public interface JavaWebService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices.thesis.enesuysal.ist/JavaWebService/GetObjectSOARequest", ReplyAction="http://WebServices.thesis.enesuysal.ist/JavaWebService/GetObjectSOAResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CSharpClientConsoleTestApp.SOAWebServiceReference.GetObjectSOAResponse GetObjectSOA(CSharpClientConsoleTestApp.SOAWebServiceReference.GetObjectSOARequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices.thesis.enesuysal.ist/JavaWebService/GetObjectSOARequest", ReplyAction="http://WebServices.thesis.enesuysal.ist/JavaWebService/GetObjectSOAResponse")]
        System.Threading.Tasks.Task<CSharpClientConsoleTestApp.SOAWebServiceReference.GetObjectSOAResponse> GetObjectSOAAsync(CSharpClientConsoleTestApp.SOAWebServiceReference.GetObjectSOARequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WebServices.thesis.enesuysal.ist/")]
    public partial class employee : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private ushort genderField;
        
        private sbyte ageField;
        
        private bool isSingleField;
        
        private int weightField;
        
        private double heightField;
        
        private string eyeColorField;
        
        private float salaryField;
        
        private string houseNumberField;
        
        private string floorNumberField;
        
        private string streetField;
        
        private string cityField;
        
        private string zipField;
        
        private string countryField;
        
        private short countryCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ushort gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
                this.RaisePropertyChanged("gender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public sbyte age {
            get {
                return this.ageField;
            }
            set {
                this.ageField = value;
                this.RaisePropertyChanged("age");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool isSingle {
            get {
                return this.isSingleField;
            }
            set {
                this.isSingleField = value;
                this.RaisePropertyChanged("isSingle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
                this.RaisePropertyChanged("weight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
                this.RaisePropertyChanged("height");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string eyeColor {
            get {
                return this.eyeColorField;
            }
            set {
                this.eyeColorField = value;
                this.RaisePropertyChanged("eyeColor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public float salary {
            get {
                return this.salaryField;
            }
            set {
                this.salaryField = value;
                this.RaisePropertyChanged("salary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string houseNumber {
            get {
                return this.houseNumberField;
            }
            set {
                this.houseNumberField = value;
                this.RaisePropertyChanged("houseNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string floorNumber {
            get {
                return this.floorNumberField;
            }
            set {
                this.floorNumberField = value;
                this.RaisePropertyChanged("floorNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("street");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
                this.RaisePropertyChanged("zip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public short countryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
                this.RaisePropertyChanged("countryCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetObjectSOA", WrapperNamespace="http://WebServices.thesis.enesuysal.ist/", IsWrapped=true)]
    public partial class GetObjectSOARequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices.thesis.enesuysal.ist/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CSharpClientConsoleTestApp.SOAWebServiceReference.employee name;
        
        public GetObjectSOARequest() {
        }
        
        public GetObjectSOARequest(CSharpClientConsoleTestApp.SOAWebServiceReference.employee name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetObjectSOAResponse", WrapperNamespace="http://WebServices.thesis.enesuysal.ist/", IsWrapped=true)]
    public partial class GetObjectSOAResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices.thesis.enesuysal.ist/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public GetObjectSOAResponse() {
        }
        
        public GetObjectSOAResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface JavaWebServiceChannel : CSharpClientConsoleTestApp.SOAWebServiceReference.JavaWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JavaWebServiceClient : System.ServiceModel.ClientBase<CSharpClientConsoleTestApp.SOAWebServiceReference.JavaWebService>, CSharpClientConsoleTestApp.SOAWebServiceReference.JavaWebService {
        
        public JavaWebServiceClient() {
        }
        
        public JavaWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JavaWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JavaWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JavaWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CSharpClientConsoleTestApp.SOAWebServiceReference.GetObjectSOAResponse CSharpClientConsoleTestApp.SOAWebServiceReference.JavaWebService.GetObjectSOA(CSharpClientConsoleTestApp.SOAWebServiceReference.GetObjectSOARequest request) {
            return base.Channel.GetObjectSOA(request);
        }
        
        public string GetObjectSOA(CSharpClientConsoleTestApp.SOAWebServiceReference.employee name) {
            CSharpClientConsoleTestApp.SOAWebServiceReference.GetObjectSOARequest inValue = new CSharpClientConsoleTestApp.SOAWebServiceReference.GetObjectSOARequest();
            inValue.name = name;
            CSharpClientConsoleTestApp.SOAWebServiceReference.GetObjectSOAResponse retVal = ((CSharpClientConsoleTestApp.SOAWebServiceReference.JavaWebService)(this)).GetObjectSOA(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CSharpClientConsoleTestApp.SOAWebServiceReference.GetObjectSOAResponse> CSharpClientConsoleTestApp.SOAWebServiceReference.JavaWebService.GetObjectSOAAsync(CSharpClientConsoleTestApp.SOAWebServiceReference.GetObjectSOARequest request) {
            return base.Channel.GetObjectSOAAsync(request);
        }
        
        public System.Threading.Tasks.Task<CSharpClientConsoleTestApp.SOAWebServiceReference.GetObjectSOAResponse> GetObjectSOAAsync(CSharpClientConsoleTestApp.SOAWebServiceReference.employee name) {
            CSharpClientConsoleTestApp.SOAWebServiceReference.GetObjectSOARequest inValue = new CSharpClientConsoleTestApp.SOAWebServiceReference.GetObjectSOARequest();
            inValue.name = name;
            return ((CSharpClientConsoleTestApp.SOAWebServiceReference.JavaWebService)(this)).GetObjectSOAAsync(inValue);
        }
    }
}
