//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpClientTestApp.CSharpWebServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CSharpWebServiceReference.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name value from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetResult", ReplyAction="*")]
        CSharpClientTestApp.CSharpWebServiceReference.GetResultResponse GetResult(CSharpClientTestApp.CSharpWebServiceReference.GetResultRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetResult", ReplyAction="*")]
        System.Threading.Tasks.Task<CSharpClientTestApp.CSharpWebServiceReference.GetResultResponse> GetResultAsync(CSharpClientTestApp.CSharpWebServiceReference.GetResultRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResult", Namespace="http://tempuri.org/", Order=0)]
        public CSharpClientTestApp.CSharpWebServiceReference.GetResultRequestBody Body;
        
        public GetResultRequest() {
        }
        
        public GetResultRequest(CSharpClientTestApp.CSharpWebServiceReference.GetResultRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetResultRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string value;
        
        public GetResultRequestBody() {
        }
        
        public GetResultRequestBody(string value) {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResultResponse", Namespace="http://tempuri.org/", Order=0)]
        public CSharpClientTestApp.CSharpWebServiceReference.GetResultResponseBody Body;
        
        public GetResultResponse() {
        }
        
        public GetResultResponse(CSharpClientTestApp.CSharpWebServiceReference.GetResultResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetResultResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object GetResultResult;
        
        public GetResultResponseBody() {
        }
        
        public GetResultResponseBody(object GetResultResult) {
            this.GetResultResult = GetResultResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : CSharpClientTestApp.CSharpWebServiceReference.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<CSharpClientTestApp.CSharpWebServiceReference.WebServiceSoap>, CSharpClientTestApp.CSharpWebServiceReference.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CSharpClientTestApp.CSharpWebServiceReference.GetResultResponse CSharpClientTestApp.CSharpWebServiceReference.WebServiceSoap.GetResult(CSharpClientTestApp.CSharpWebServiceReference.GetResultRequest request) {
            return base.Channel.GetResult(request);
        }
        
        public object GetResult(string value) {
            CSharpClientTestApp.CSharpWebServiceReference.GetResultRequest inValue = new CSharpClientTestApp.CSharpWebServiceReference.GetResultRequest();
            inValue.Body = new CSharpClientTestApp.CSharpWebServiceReference.GetResultRequestBody();
            inValue.Body.value = value;
            CSharpClientTestApp.CSharpWebServiceReference.GetResultResponse retVal = ((CSharpClientTestApp.CSharpWebServiceReference.WebServiceSoap)(this)).GetResult(inValue);
            return retVal.Body.GetResultResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CSharpClientTestApp.CSharpWebServiceReference.GetResultResponse> CSharpClientTestApp.CSharpWebServiceReference.WebServiceSoap.GetResultAsync(CSharpClientTestApp.CSharpWebServiceReference.GetResultRequest request) {
            return base.Channel.GetResultAsync(request);
        }
        
        public System.Threading.Tasks.Task<CSharpClientTestApp.CSharpWebServiceReference.GetResultResponse> GetResultAsync(string value) {
            CSharpClientTestApp.CSharpWebServiceReference.GetResultRequest inValue = new CSharpClientTestApp.CSharpWebServiceReference.GetResultRequest();
            inValue.Body = new CSharpClientTestApp.CSharpWebServiceReference.GetResultRequestBody();
            inValue.Body.value = value;
            return ((CSharpClientTestApp.CSharpWebServiceReference.WebServiceSoap)(this)).GetResultAsync(inValue);
        }
    }
}
